<a href="https://colab.research.google.com/github/Usmanimaaz12/assignments/blob/Module-2/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
import numpy as np
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]
arr=np.array([my_list1,my_list2,my_list3]) #focus on square bracket

In [74]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [75]:
arr.shape

(3, 5)

In [76]:
arr.reshape(5,3)                #original array not updated until we do arr=arr.reshape(5,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [77]:
arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [78]:
arr.shape

(3, 5)

In [79]:
arr[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [80]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [81]:
arr[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [82]:
arr[1:2,1:4]

array([[7, 8, 9]])

In [83]:
arr1=np.arange(0,10,step=2)

In [84]:
arr1


array([0, 2, 4, 6, 8])

In [85]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [86]:
##copy function and braodcasting
arr2=np.array([1,2,3,4,5,6,7,8,9,10])

In [87]:
arr2[3:]=100

In [88]:
arr2                        #if we do not use copy function then same memory cell stores the vale of both arrays and updation affects both.


array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [89]:
arr3=arr2.copy()
arr3

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [91]:

arr<2

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [92]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [95]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
np.random.rand(3,3)

array([[0.06211058, 0.43201528, 0.69623417],
       [0.45317184, 0.2510603 , 0.07755152],
       [0.28639143, 0.92398008, 0.53052608]])

In [97]:
np.random.randn(3,3)

array([[-0.09147791,  0.14635435, -0.84638438],
       [ 0.21424915,  1.16150508,  1.14119231],
       [-1.00079313, -1.24147612, -0.84136465]])

In [98]:
np.random.randint(0,100,8)

array([49, 20, 67, 20, 88, 19, 68,  1])

In [100]:
np.random.random_sample((1,5))

array([[0.20084299, 0.450584  , 0.46533606, 0.79533408, 0.65690503]])